### ISSUE TITLE
Can't search mgwt source code on github

### ISSUE THREAD

**Issue by aaboyd** [mgwt/mgwt#225]
I recently ran across some problems that forced me to dig into the source code.  I tried searching for some text that I received in an error message.

[mgwt/mgwt](https://github.com/mgwt/mgwt/) is a fork and therefore it's source cannot be searched.  Is there anyway that github can change this?

**Comment by waynedyck** [comment]
Not an issue related to the mgwt repo. Something that would need to be taken up with GitHub.
