### ISSUE TITLE
In mgwt.themebase: customising main.css has no effect

### ISSUE THREAD

**Issue by florian-f** [mgwt/mgwt#244]
When I tried to modify for example `body` in the main.css, it wouldn't have any effect.
As it turns out the path to the 'original' MainResourceAppearance was wrong (see pull request).

What strikes me as odd here is that the compiler didn't even produce a warning. Thus, it took me quite some time to figure out what was actually wrong (and it's probably why this could go unnoticed for so long).

**Comment by Jul13nT** [comment]
Thanks for the tip, I was struggling with this too !

**Comment by waynedyck** [comment]
Fixed with commit https://github.com/mgwt/mgwt.themebase/commit/72bda1637c46cab024e0e964d45ebe37fe19381e
