### ISSUE TITLE
mgwt2.0 - Chrome v43 (Beta) displays header height wrong

### ISSUE THREAD

**Issue by luxmar** [mgwt/mgwt#255]
In Chrome v.43 the header / footer height is too small (height property in CSS will ignored), if the content is higher than the screen size.

Image from current showcase when content is higher:
![2015-04-30 09 19 14](https://cloud.githubusercontent.com/assets/7394438/7427213/ddbc13aa-efd6-11e4-8824-0275c5c4dec8.png)

If content is not higher, the header will be displayed correct:
![2015-04-30 09 19 22](https://cloud.githubusercontent.com/assets/7394438/7427225/122a79c4-efd7-11e4-958e-246add255828.png)

To fix this problem, replace in the CSS the "height" property with "min-height".

**Comment by luxmar** [comment]
see also chormium issue for beta 43:
https://code.google.com/p/chromium/issues/detail?id=484575

**Comment by schteff** [comment]
According to the chromium issue thread it has been fixed in v44.

**Comment by schteff** [comment]
Sadly still happens in version 45. But in Chrome Canary version 46 it seems to be resolved.

**Comment by waynedyck** [comment]
Are you still seeing this in the latest Chrome updates?

**Comment by schteff** [comment]
No it seems like it is fixed now (since about version 46). I have v48 on my phone and it works fine.

**Comment by waynedyck** [comment]
Cool. I have 48 as well and it seems fine from what I can tell. Thanks.

Fixed since Chrome 46.
