### ISSUE TITLE
PullPanel squeezes the tabbar everytime the it updates

### ISSUE THREAD

**Issue by ruhaim** [mgwt/mgwt#260]
Initial appearance
![](http://i.imgur.com/XOzDaBB.png)

After several pull to refresh attempts
![](http://i.imgur.com/qQoxOn2.png)

**Comment by luxmar** [comment]
duplicate of https://github.com/mgwt/mgwt/issues/255

**Comment by waynedyck** [comment]
This has been fixed with the latest versions of Chrome.
