### ISSUE TITLE
MDateBox in ShowCase on iPhone iOS 9.2 not working

### ISSUE THREAD

**Issue by waynedyck** [mgwt/mgwt#278]
MDateBox does not work on iPhone, no DatePicker pops up. It pops up on iPad, just not on iPhone.

Referencing [MDateBox in ShowCase on iPhone behaving wrong](https://groups.google.com/forum/#!topic/mgwt/JE4bjDeSPIA) and [DatePicker not closing in iOS when click another field](https://groups.google.com/forum/#!msg/mgwt/Tc90SQZjaek/b_cbAmB0FQAJ) discussion topics on mgwt Google Group.

**Comment by waynedyck** [comment]
- The current code still basically works on iOS 8.4 but is totally non responsive on iOS 9.2.
- Tested a plain HTML file with a <input type="date"> field on an iOS 9.2 iPhone and it works correctly so I think it has something to do with the way MGWT is setting up the element.

**Comment by waynedyck** [comment]
Have changes working now with iOS 9.2 iPhone device. Need to test on other versions of iOS.

**Comment by waynedyck** [comment]
Confirmed changes working with iOS 8.4 iPhone device.

**Comment by paulfrench** [comment]
Hello Wayne,

Still knee deep in work at mo. Hope to surface in a few weeks. I have a vague memory of the mdatebox not working correctly but it depended on whether it was in a ScrollPanel and possibly if you applied the screen no bounce fix. I can't remember at the mo but will dig about if need be. What is your current solution?

Cheers

**Comment by paulfrench** [comment]
Opps.... Accidentally closed

**Comment by waynedyck** [comment]
There is different code to setup the MDateBox on the iPhone compared to the iPad. From the comments it would appear to have something to do with an issue in iOS 7; that issue does not present itself in subsequent versions of iOS that I have been able to see.

At the moment I have simply replaced the code with similar code to the iPad and it seems to work fine.

I'll run more tests on it tonight and if it seems solid will push the commits likely this weekend.

**Comment by paulfrench** [comment]
Hello Wayne,


I dug this out. We hit all sorts of issues with MDateBox. Compare it with MDateBox to see the changes we made. They should be relevant.


Cheers






Sent from Windows Mail





From: Wayne Dyck
Sent: ‎Thursday‎, ‎25‎ ‎February‎ ‎2016 ‎14‎:‎36
To: mgwt/mgwt
Cc: Paul French




There is different code to setup the MDateBox on the iPhone compared to the iPad. From the comments it would appear to have something to do with an issue in iOS 7; that issue does not present itself in subsequent versions of iOS that I have been able to see.

At the moment I have simply replaced the code with similar code to the iPad and it seems to work fine.

I'll run more tests on it tonight and if it seems solid will push the commits likely this weekend.

**Comment by waynedyck** [comment]
Do you mean check the commit logs on MDateBox?

**Comment by paulfrench** [comment]
Sorry Wayne. No I meant compare the attachment to current mdatebox. It is basically a copy of mdatebox with changes. I'm being lazy (coz under pressure at work) but I can create a quick branch for you to look at. Let me know

-----Original Message-----

**Comment by waynedyck** [comment]
Oh, that would explain it. I didn't see any attachment with your email.

**Comment by paulfrench** [comment]
[DateBox.zip](https://github.com/mgwt/mgwt/files/147906/DateBox.zip)

Sorry Wayne. I did send the attachment as part of the email but it seems to have been blocked probably because githib here do not allow .java files as attachments? Here it is zipped up.

Ta

**Comment by waynedyck** [comment]
Brilliant. I'll have a look at it. Thanks!

**Comment by waynedyck** [comment]
Was looking at it this morning and incorporates several of the changes I was making as well. I used some of your changes as well knowing that these changes should work on a Windows phone, correct?

**Comment by waynedyck** [comment]
The date picker works correctly on iOS and Android devices I have tested. However, I was not able to get the placeholder text to display.

As it turns out this is by design; [HTML5 does not allow the placeholder attribute on input[type="date"]](http://w3c.github.io/html/sec-forms.html#date-state-typedate).

**Comment by paulfrench** [comment]
Windows phone has rubbish support for native date. It does not support type=date. The fixes were for iphone and iPad if I remember. Anyway sounds like you have sorted it. Cheers

-----Original Message-----

**Comment by waynedyck** [comment]
Thanks for your file to review as well. It helped confirm some of the changes I was thinking with what you had also done.
