### ISSUE TITLE
Carousel setSupportCarouselIndicatorTap(true) throws an exception

### ISSUE THREAD

**Issue by volgin** [mgwt/mgwt#280]
This line of code:

    `carousel.setSupportCarouselIndicatorTap(true);`

 throws an exception at this point:

   ` carouselIndicatorContainer.setHandleTapEvent(supportCarouselIndicatorTap);`

as carouselIndicatorContainer is undefined. Setting 

    `carousel.setSupportCarouselIndicatorTap(false);`

avoids this exception as keeping the default value prevents this line of code from being reached.

Looking at the source code I see that carouselIndicatorContainer is initialized only in one place - in refresh(), and only after a delay. So the workaround for this bug looks like this:

```
carousel.refresh();
Timer timer = new Timer() {
    @Override
    public void run() {
        carousel.setSupportCarouselIndicatorTap(true);
    }
};
timer.schedule(300);
```

**Comment by paulfrench** [comment]
done but part of pull request #288

**Comment by paulfrench** [comment]
merged in
