### ISSUE TITLE
Iconbuttons not displayed on MS Edge Browser

### ISSUE THREAD

**Issue by luxmar** [mgwt/mgwt#282]
The Iconbuttons are not displayed on MS Edge Browser any more. Only grey squares.

see also
#262 - Pull request
and
https://groups.google.com/forum/#!topic/mgwt/EkSoOF89MPA - Google Groups

**Comment by luxmar** [comment]
The User Agent changed on MS Edge from 12 to 13.
After changing the Line #161 in OsDetectionRuntimeImpl.java to
`    if (userAgent.contains("edge/12") || userAgent.contains("edge/13")) {`
it works again on MS Edge.

**Comment by paulfrench** [comment]
This has been fixed
