### ISSUE TITLE
longTapEvent.getStartPositions().get(0) returns Touch instance corresponding to the finger fired the very first LongTapEvent on the element, regardless of how many long taps where performed

### ISSUE THREAD

**Issue by dankurka** [mgwt/mgwt#8]
Moved from: https://code.google.com/p/mgwt/issues/detail?id=297

longTapEvent.getStartPositions().get(0) returns Touch instance corresponding to the finger fired the very first LongTapEvent on the element, regardless of how many long taps where performed.

Should reset startPositions array in LongTapRecognizer.

**Comment by robert4os** [comment]
It was not fixed or it reemerged. See https://github.com/mgwt/mgwt/pull/267
